name: Release and push to github

on:
  workflow_dispatch:

jobs:
  cf2:
   runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build
        run: docker run --rm -v ${PWD}:/module bitcraze/builder bash -c "make defconfig && ./tools/build/build PLATFORM=cf2 UNIT_TEST_STYLE=min"
