name: Release and push to github

on:
  workflow_dispatch:

jobs:
  cf2:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: build
      run: docker run --rm -v ${PWD}:/module bitcraze/builder bash -c "make defconfig && ./tools/build/build PLATFORM=cf2 UNIT_TEST_STYLE=min"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: cf2-${{ github.ref_name }}
        path: cf2.bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Upload CF2 bin
        uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: cf2.bin
        asset_name: cf2.bin
        asset_content_type: application/octet-stream
